'use strict';

const INCREASE_HOUR = 'INCREASE_HOUR';

const INCREASE_MINUTE = 'INCREASE_MINUTE';

const INCREASE_SECOND = 'INCREASE_SECOND';

const INCREASE_YEAR = 'INCREASE_YEAR';

const INCREASE_MONTH = 'INCREASE_MONTH';

const INCREASE_DAY = 'INCREASE_DAY';

const RESET_MONTH = 'RESET_MONTH';

const RESET_DAY = 'RESET_DAY';

const CHANGE_TIMEZONE = 'CHANGE_TIMEZONE';

const CLEAR_TIMEZONETEXT = 'CLEAR_TIMEZONETEXT';

module.exports = {
  INCREASE_HOUR,
  INCREASE_MINUTE,
  INCREASE_SECOND,
  INCREASE_YEAR,
  INCREASE_MONTH,
  INCREASE_DAY,
  RESET_MONTH,
  RESET_DAY,
  CHANGE_TIMEZONE,
  CLEAR_TIMEZONETEXT,
};
