'use strict';

const INCREASE_HOUR = 'INCREASE_HOUR';

const INCREASE_MINUTE = 'INCREASE_MINUTE';

const INCREASE_SECOND = 'INCREASE_SECOND';

const CHANGE_LOCATION = 'CHANGE_LOCATION';

module.exports = {
  INCREASE_HOUR,
  INCREASE_MINUTE,
  INCREASE_SECOND,
  CHANGE_LOCATION,
};
