'use strict';

const ADD_TIMEZONE = 'ADD_TIMEZONE';

const CHANGE_TIMEZONE = 'CHANGE_TIMEZONE';

const CLEAR_TIMEZONETEXT = 'CLEAR_TIMEZONETEXT';

module.exports = {
  ADD_TIMEZONE,
  CHANGE_TIMEZONE,
  CLEAR_TIMEZONETEXT,
};
