'use strict';

/**
 * Login
 */
const LOGIN_START = 'LOGIN_START';

/**
 *
 */
const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';

/**
 *
 */
const LOGIN_FAILURE = 'LOGIN_FAILURE';

const REGISTER_START = 'REGISTER_START';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAIL = 'REGISTER_FAIL';

const LOGOUT_START = 'LOGOUT_START';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
const LOGOUT_FAILURE = 'LOGOUT_FAILURE';


module.exports = {
  LOGIN_START,
  LOGIN_SUCCESSFUL,
  LOGIN_FAILURE,

  REGISTER_START,
  REGISTER_SUCCESS,
  REGISTER_FAIL,

  LOGOUT_START,
  LOGOUT_SUCCESS,
  LOGOUT_FAILURE,
};
